### ISSUE TITLE
engine_type seems to support only ActiveMQ

### ISSUE THREAD

**Issue by leriel** [cloudposse/terraform-aws-mq-broker#18]
Found a bug? Maybe our [Slack Community](https://slack.cloudposse.com) can help. 

[![Slack Community](https://slack.cloudposse.com/badge.svg)](https://slack.cloudposse.com)

## Describe the Bug
[Documentation](https://github.com/cloudposse/terraform-aws-mq-broker/blob/a713c203030c88c549045e7b7f20dc22761c0dd3/README.md) states that `engine_type` can be ActiveMQ or RabbitMQ. Despite that, creation of the resource with `engine_type = "RabbitMQ"` fails. I can see that at the time of writing (2021-03-08), this module uses `aws_mq_broker` under the hood, which does not support RabbitMQ yet (see https://github.com/hashicorp/terraform-provider-aws/pull/16108). Probably this is just documentation issue, but if there is a way to spin up aws RabbitMQ broker, please advise. Thanks in advance!

## Expected Behavior
Successful creation of the resource

## Steps to Reproduce
1. Create resource using module:
```
module "mq_broker" {
  source = "cloudposse/mq-broker/aws"
  namespace                    = "ns"
  stage                        = "test"
  name                         = "rabbit"
  apply_immediately            = true
  auto_minor_version_upgrade   = true
  deployment_mode              = "SINGLE_INSTANCE"
  engine_type                  = "RabbitMQ"
  engine_version               = "3.8.6"
  host_instance_type           = "mq.t3.micro"
  publicly_accessible          = true
  general_log_enabled          = true
  audit_log_enabled            = true
  use_existing_security_groups = true
  existing_security_groups     = [aws_security_group.my.id]
  encryption_enabled           = false
  use_aws_owned_key            = false
  vpc_id                       = data.aws_vpc.my_vpc.id
  subnet_ids                   = data.aws_subnet_ids.my_vpc.ids
  mq_application_user          = data.aws_ssm_parameter.app_login.value
  mq_application_password      = data.aws_ssm_parameter.app_password.value
  mq_admin_user                = data.aws_ssm_parameter.admin_login.value
  mq_admin_password            = data.aws_ssm_parameter.admin_password.value
}

```
2. Run `terraform apply`
3. Enter `yes`
```
Error: expected engine_type to be one of [ACTIVEMQ], got RabbitMQ

  on .terraform/modules/mq_broker/main.tf line 71, in resource "aws_mq_broker" "default":
  71:   engine_type                = var.engine_type
```

## Screenshots
If applicable, add screenshots or logs to help explain your problem.

## Environment (please complete the following information):

Anything that will help us triage the bug will help. Here are some ideas:
- OSX 11.2.1
 - `terraform --version`
 ```
terraform --version
Terraform v0.14.7
+ provider registry.terraform.io/hashicorp/aws v3.31.0
+ provider registry.terraform.io/hashicorp/null v3.1.0
+ provider registry.terraform.io/hashicorp/random v3.1.0
+ provider registry.terraform.io/hashicorp/template v2.2.0
```

## Additional Context
-

**Comment by leigh507** [comment]
This is due to the terrafor-aws-provider 3.31.0 not including the changes to add the rabbitMQ broker. [Here](https://github.com/hashicorp/terraform-provider-aws/pull/16108) is the RD that adds rabbitmq to the provider and has been earmarked for the 3.32.0 release.

**Comment by Gowiem** [comment]
@leigh507 @leriel are you gents still seeing this with `3.32.0`? Seems we are good to close this one out with the release of 3.32, but want to confirm before doing so.
