### ISSUE TITLE
Module enabled toggle is not implemented in main and outputs files

### ISSUE THREAD

**Issue by sumitg892** [cloudposse/terraform-aws-mq-broker#19]
In the documentation, it says we can use enabled to disable/enable the resource creation, however, it has not been fully implemented. Can someone please look into it?

**Comment by treksler** [comment]
PR https://github.com/cloudposse/terraform-aws-mq-broker/pull/20

**Comment by Gowiem** [comment]
Closed by #20 -- Thanks @treksler 👍
