### ISSUE TITLE
BadRequestException: Specify exactly one user for engine type [RABBITMQ]

### ISSUE THREAD

**Issue by sumitg892** [cloudposse/terraform-aws-mq-broker#21]
When we use this module for creating Rabbitmq, we get an unexpected error in our terraform application:

Error: BadRequestException: Specify exactly one user for engine type [RABBITMQ].
{
  RespMetadata: {
    StatusCode: 400,
    RequestID: "128ea9ae-c2b6-4a3e-a644-2cc3470a2b1a"
  },
  ErrorAttribute: "users",
  Message_: "Specify exactly one user for engine type [RABBITMQ]."
}

## Expected Behavior
No bugs, should work fine.

## Steps to Reproduce
Run the terraform using this module for RabbitMQ

**Comment by Gowiem** [comment]
Closed by #22
